name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  compile:
    name: Compile Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Compile the project
        run: mvn --batch-mode clean compile

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Test the project
        run: mvn --batch-mode test
      - name: Verify the project
        run: mvn --batch-mode --update-snapshots verify

  build-artifact:
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Package the project
        run: mvn --batch-mode clean package -DskipTests
      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifact
          path: target/*.jar

  docker-build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [build-artifact]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged-artifact
          path: target/

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:${{ github.sha }}
#